import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Carousal from '../components/Carousal'
import Products from '../components/Products'

const inter = Inter({ subsets: ['latin'] })

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' max-w-screen-2xl'>
        <Header/>
        <Carousal/>
        <Products products={products}/>
      </main>
    </>
  )
}

export const getServerSideProps = async(context) => {
  const products = await fetch('https://fakestoreapi.com/products').then(
    (res) => res.json()
  )

  return {
    props:{
      products:products
    }
  }
}